### PR TITLE
solve equation function added 

### PR DESCRIPTION
**Pull request by kanikaa-3018**
user has to input 3 comma separated values to solve the quadratic equation, else error is thrown

### CODE REVIEW

**Review by DhanushNehru — CHANGES_REQUESTED** [review]
Hi @kanikaa-3018 

Please have that function on the right button view, the UI seems misaligned

**Comment by kanikaa-3018** [comment]
pls check if its fine now

**Review by DhanushNehru — CHANGES_REQUESTED** [review]
Please move that button itself to the right side , @kanikaa-3018

**Comment by kanikaa-3018** [comment]
i have completed it, pls check now

**Comment by kanikaa-3018** [comment]
sir the button is on the right side, how shall i move it further? could u pls elaborate

**Comment by DhanushNehru** [comment]
Looks fine , Thanks for your contribution @kanikaa-3018

**Pull request merged**
