### PR TITLE
Updated Desgin

### PR DESCRIPTION
**Pull request by CleverOscar**
I went ahead and added TailwindCSS through cdn and manage to turn the application to look exactly like the design. 

Please let me know if the changes are valid. 

## Example of the updated development 
Hacktoberfest-calculator01

### CODE REVIEW

**Comment by DhanushNehru** [comment]
But viewing it by mobile makes the keys to be overlapped

**Comment by CleverOscar** [comment]
Yea I couldn't really think of a mobile design on the fly, wasn't sure how the mobile view is suppose to look. But I'd be more than happy to make the changes for mobile view

**Comment by DhanushNehru** [comment]
Checked the code currently, the mobile view kind of responsiveness is already been implemented

**Comment by CleverOscar** [comment]
I have updated the mobile view, please let me know if the changes are valid

**Comment by DhanushNehru** [comment]
Many new functionalities like binary, decimal etc was included & it seems not there

And the design is changed currently kindly recheck

**Comment by CleverOscar** [comment]
I see, it seems like only two more buttons were added, are those the only changes that need to be made?

**Comment by DhanushNehru** [comment]
The buttons are not working & there are many merge conflicts

Try improving the existing updated code design if needed

**Comment by CleverOscar** [comment]
Got it, well thank you for your time!

**Comment by DhanushNehru** [comment]
You are welcome @CleverOscar 🙂

**Pull request closed without merging**
