### PR TITLE
Add pi button

### PR DESCRIPTION
**Pull request by Tarun-k-Gupta**
Please also add Hacktoberfest label to it.

### CODE REVIEW

**Comment by DhanushNehru** [comment]
Please share a screenshot of your implementation

**Comment by DhanushNehru** [comment]
And re raise your PR

**Review by DhanushNehru — COMMENTED** [review]
Please re raise your PR with screenshots of your implementation

**Comment by Tarun-k-Gupta** [comment]
@DhanushNehru  implementations meaning the code or the screen of the calculator showing Pi button?

**Comment by DhanushNehru** [comment]
Just screenshot of the screen would be fine

Make a PR again please, with screenshot of your PI button

**Pull request merged**
