### PR TITLE
changed error stylings,history and textbox

### PR DESCRIPTION
**Pull request by kmahesh18**
image
added sounds to keys and error stylings
also modified history table and textbox cursor

### CODE REVIEW

**Review by DhanushNehru — CHANGES_REQUESTED** [review]
Each time a number is typed its getting typed twice please check that @kmahesh18

**Comment by DhanushNehru** [comment]
There is some functional logic as mentioned above, also merge conflicts to be fixed @kmahesh18

**Comment by kmahesh18** [comment]
conflicts and function issues are solved .. recheck pr

**Comment by kmahesh18** [comment]
> When you click on a number, instead of displaying once it gets displayed twice. @kmahesh18
> 
> As per the below image number `8` was clicked once
> 
> Screenshot 2024-10-21 at 1 40 59 PM

Ohh...sorry...I'll update the functionality and pr

**Pull request closed without merging**
