### PR TITLE
Add backspace button

### PR DESCRIPTION
**Pull request by SaadOps**
Added a backspace button successfully which cuts numbers one by one and clears the input field if it contains a string.
#89 Resolved

### CODE REVIEW

**Comment by DhanushNehru** [comment]
Please resolve the merge conflicts @SaadOps

**Comment by SaadOps** [comment]
> Please resolve the merge conflicts @SaadOps

Done :)

**Review by selemondev — COMMENTED** [review]
Code reviewed.

**Comment by selemondev** [comment]
Thank you @SaadOps for your contribution.

**Pull request merged**
