### PR TITLE
Implemented the gamma function. Issue #143

### PR DESCRIPTION
**Pull request by Abhik004**
I successfully integrated the gamma function into a JavaScript application. I also fixed a bug - the buttons for more function were repeated twice. I have resolved the issue and fixed the bug.

### CODE REVIEW

**Comment by Abhik004** [comment]
Kindly check it and merge it if its ok @DhanushNehru

**Comment by DhanushNehru** [comment]
Please resolve merge conflicts @Abhik004 

#145

**Review by DhanushNehru — CHANGES_REQUESTED** [review]
Adding this makes the alignment improper, please check @Abhik004 

Screenshot 2024-10-19 at 3 04 29 PM

**Comment by Abhik004** [comment]
I will create a new pr resolving the bug

**Pull request closed without merging**
